### ISSUE TITLE
codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by karye** [MikhailKravets/mkdocs_puml#22]
**Describe the bug**
When running MKdocs-material with the mkdocs_puml plugin.
Pages include several puml-blocks like this:
```puml
@startuml
!theme plain
skinparam classAttributeIconSize 0
skinparam defaultFontName "Roboto, Helvetica"
hide circle
object Bibliotek
object Bok
object Lån
object Kund
object Sökresultat
@enduml
```

**To Reproduce**
Strangely, sometimes it works, sometime not.

**Expected behavior**
Run without any error.

**Error output**
Traceback (most recent call last):
  File "/home/pi/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs/commands/build.py", line 311, in build
    env = config.plugins.run_event('env', env, config=config, files=files)
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs/plugins.py", line 520, in run_event
    result = method(item, **kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs_puml/plugin.py", line 104, in on_env
    resp = self.puml.translate(self.diagrams.values())
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs_puml/puml.py", line 55, in translate
    return [self.postprocess(v) for v in svg_images]
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs_puml/puml.py", line 55, in <listcomp>
    return [self.postprocess(v) for v in svg_images]
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/mkdocs_puml/puml.py", line 100, in request
    return resp.content.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Desktop (please complete the following information):**
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Additional context**
Package                                   Version
----------------------------------------- ----------
Babel                                     2.12.1
bracex                                    2.3.post1
certifi                                   2022.12.7
chardet                                   5.1.0
charset-normalizer                        2.1.1
click                                     8.1.3
colorama                                  0.4.6
colorzero                                 2.0
distro                                    1.8.0
ghp-import                                2.1.0
gitdb                                     4.0.10
GitPython                                 3.1.31
gpiozero                                  1.6.2
httplib2                                  0.21.0
idna                                      3.4
importlib-metadata                        6.0.0
Jinja2                                    3.1.2
Markdown                                  3.3.7
MarkupSafe                                2.1.2
mdx-truly-sane-lists                      1.3
mergedeep                                 1.3.4
mkdocs                                    1.4.2
mkdocs-awesome-pages-plugin               2.8.0
mkdocs-git-revision-date-localized-plugin 1.2.0
mkdocs-material                           9.1.2
mkdocs-material-extensions                1.1.1
mkdocs_puml                               1.1.1
natsort                                   8.3.1
packaging                                 23.0
pip                                       23.0.1
pipdeptree                                2.5.2
Pygments                                  2.14.0
pymdown-extensions                        9.10
pyparsing                                 3.0.9
python-apt                                2.2.1
python-dateutil                           2.8.2
pytz                                      2022.7.1
PyYAML                                    6.0
pyyaml_env_tag                            0.1
regex                                     2022.10.31
requests                                  2.28.2
RPi.GPIO                                  0.7.1
setuptools                                67.6.0
six                                       1.16.0
smmap                                     5.0.0
spidev                                    3.6
ssh-import-id                             5.11
toml                                      0.10.2
urllib3                                   1.26.15
watchdog                                  2.3.1
wcmatch                                   8.4.1
wheel                                     0.38.4
zipp                                      3.15.0

**Comment by MikhailKravets** [comment]
Hi @karye , thank for raising an issue. I will take a look asap.
