### ISSUE TITLE
mkdocs 1.5.0 breaks compatibility

### ISSUE THREAD

**Issue by bmcandr** [MikhailKravets/mkdocs_puml#31]
**Describe the bug**
`mkdocs` released v1.5.0 yesterday and it breaks compatibility with `mkdocs-puml` which allows dependencies up to <2.0.

**To Reproduce**
Try to `mkdocs build` with `mkdocs==1.5.0`.

**Expected behavior**
Successful build.

**Desktop (please complete the following information):**
 - OS: linux (GitLab CI runner)
 - `python~=3.8`
 - `mkdocs==1.5.0`

**Additional context**
Trace:

```
File "/usr/local/lib/python3.8/site-packages/mkdocs_autorefs/plugin.py", line 23, in <module>
    from mkdocs.utils import warning_filter
  File "/usr/local/lib/python3.8/site-packages/mkdocs/utils/__init__.py", line 453, in __getattr__
    warnings.warn(
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/__main__.py", line 283, in build_command
    cfg = config.load_config(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 378, in load_config
    errors, warnings = cfg.validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 230, in validate
    run_failed, run_warnings = self._validate()
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 182, in validate
    return self.run_validation(value)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1054, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1090, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/usr/local/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 1108, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/usr/local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 209, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line [127](https://gitlab.com/*****/*****/-/jobs/4747916141#L127), in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/site-packages/mkdocs_puml/plugin.py", line 6, in <module>
    from mkdocs.plugins import BasePlugin, Page
ImportError: cannot import name 'Page' from 'mkdocs.plugins' (/usr/local/lib/python3.8/site-packages/mkdocs/plugins.py)
```

Pinning `mkdocs==1.4.3` in our CI config allows builds to complete successfully.

**Comment by MikhailKravets** [comment]
Thanks for raising this issue @bmcandr! I'll take a look at this asap

**Comment by MikhailKravets** [comment]
Hi @bmcandr! New release v1.2.3 was published. Please upgrade `mkdocs_puml` to the latest version
